### ISSUE TITLE
Scroll speed issue on android native browser

### ISSUE THREAD

**Issue by ashxerion** [noraesae/perfect-scrollbar#255]
I am experiencing a problem with the scroll speed on the native android browser. Works on all the other browsers I've tested on including chrome on android devices.

On the native android browser the scroll speed is much slower then the rest which becomes annoying for the user.

Anybody else who've had this problem and is there  a way to solve it?

**Comment by Robmacker** [comment]
I too am experiencing this issue. Also, on the default Android browser, I have to 'touch' the div in order to activate the scrolling ability,,,otherwise it will not scroll when page comes up.

On the Chrome browser for mobile, it works fine. I do not have to touch first.

The default scroll will work without touching the div to put the focus on it.

Hopefully you can address this as I *cannot* count on my users installing Chrome as a supplemental browser.

Thanks

**Comment by noraesae** [comment]
Hiya,

I'm afraid I've no android device and so no way to test it, but I've just tried removing the performance-critical part of the touch handler. Here is the code:

https://github.com/noraesae/perfect-scrollbar/tree/simplify-touch-handler

I'd appreciate if you test it out and check if it helps reducing the issue in the native android browser.

Cheers,

**Comment by noraesae** [comment]
Closed for inactivity.

Thanks.
