### ISSUE TITLE
Normal scrollbar not working for dropdowns when using perfect scrollbar for that div

### ISSUE THREAD

**Issue by Srinucnu** [noraesae/perfect-scrollbar#272]
Hi,
Normal scrollbar not working for dropdowns when using perfect scrollbar for that div.

i have a div with perfect scrollbar, scrollbar working fine, but my problem is scroll for dropdowns in that div is not working.

Please help me on this.

Thanks in advance.

**Comment by noraesae** [comment]
Hiya,

I've looked into the issue a little bit and maybe this is because of a patch, e9fcc0f0. The patch fixes that the scrolling event is propagated from a select element into its parent in Firefox and IE. However, I've tested in Firefox, the scrolling works fine. If it's IE problem, could you specify the environment including version and preferably some fiddle as well?

Cheers,

**Comment by noraesae** [comment]
Maybe similar to #311.
Closed for the inactivity.
