### ISSUE TITLE
Far from perfect

### ISSUE THREAD

**Issue by yairEO** [noraesae/perfect-scrollbar#279]
your javascript skills needs sharpening. This code is bloated, it shouldn't even be more than 11k top for such simple thing it does.

anyway, stop writing `var` all the time. write it once per scope. Start caching DOM objects(!!!) for example, you keep calling `$(window)` again and again. very very poorly written program. as well, stop not utilizing the power of jQuery. For example, in your code you have many places where you set `data()` again and again. you can set multiple data like so `.data({a:1,b:2,c:3})`.

These (and more) amateur mistakes are sadly preventing me (and others) from using your code...so "perfect" is not the right word to describe this project.

**Comment by MattyBalaam** [comment]
Perhaps submit some pull requests or write your own?

**Comment by yairEO** [comment]
sorry I have several projects of my own to maintain + full time job + work from the side... no time to fix code for others...wish I had but I really don't. All I can do is spare some minutes writing a list of issues i've seen from briefly looking at the source. if the author cares, he can fix these things up. if he doesn't...well...may god help us all :)

**Comment by noraesae** [comment]
Hiya,

Whoa, thank you very much for your huge suggestion. Surely I cares :smile: Actually many of them are currently in the process of modification. Here's the changes:

- About `var`, for sure I know JavaScript variable hoisting. But during the long time of development, many people have added several lines of code and now it's kinda big and mess. That's why I'm doing refactoring work, and the code will be separated into several modules which eventually makes it easier to manage the variables. Also, I know the problem of JavaScript variable hoisting is that there could be an unwanted variable reference. But the case is prevented by linting the code currently using JSHint, ESLint later, with help of CI, so there's no way that variables is used badly.
- Well, about caching variable, it's kinda a right point. But the project is already caching every jQuery DOM object except for `window` and `document` elements, as they are being used in no performance-critical part. And after refactoring, we won't use any jQuery object, so there's no need to cache `window` and `document`. For sure other elements will be cached in the same way as usual.
- I'd had no idea about the object usage in `.data()` method! Thanks for your suggestion. However the method is also not used in the refactored version, as we don't use jQuery inside the plugin.

So, now does it a little closer to *perfect*? If you have any further suggestion, please feel free to let me know!

**Comment by yairEO** [comment]
Awesome response. 
When will the next version be ready? I am eager to see the code

**Comment by noraesae** [comment]
If you'd like, you can look around the code here: #274. The release is not yet confirmed, as there's still some point to improve and I also have my main job and sadly no much time to contribute in this plugin. I'm doing my best, though.

**Comment by andri** [comment]
Good job @noraesae on this plugin. I'm using it in almost every project I do and it really is the best scrollbar script I have seen :)

**Comment by blvz** [comment]
@yairEO if you were "briefly looking at the source" here at GitHub, you could leave comments on the code itself. It's more helpful and you don't look like a dick.
