### ISSUE TITLE
No Scrollbars for Logitech Marble Mouse

### ISSUE THREAD

**Issue by slimandslam** [noraesae/perfect-scrollbar#282]
The scrollbars show up, and work fine, using my Macbook Pro trackpad.
However, when I attach a Logitech Marble Mouse to my Mac, it's as if
Perfect-Scrollbar doesn't exist (no scrollbars at all).  Any idea why 
that would happen?  It must be something with my configuration
because my Marble Mouse works fine on your demo page.

Do I need to do anything besides setting the container like this?

#scrolling_container  { 
    position: relative;
    height: 1900px;
    overflow: hidden;
}

J

**Comment by noraesae** [comment]
Hmm, I'm not sure if the logitech mouse hooks a scrollable element and do something. How about trying with a new version as you said it worked with the demo page. There's no special difference in the demo page, so the issue must be because of something other than the plugin itself.

Sorry for the late response, and thanks for reporting!

**Comment by noraesae** [comment]
Will close for the inactivity. Please feel free to reopen :smile:
