### ISSUE TITLE
 [WARN] 2015-03-05T04:31:50.387Z EventManager.fireEvent error=TypeError: undefined is not a function

### ISSUE THREAD

**Issue by hannah111029** [noraesae/perfect-scrollbar#295]
perfectscrollbar doesn't operate in "ember-cli 0.1.7.
The following error is generated.
 "[WARN] 2015-03-05T04:31:50.387Z EventManager.fireEvent error=TypeError: undefined is not a function"

this error is there related with  ember-cli version?

---------------------------------------------------------------------------------
1. brocfile.js : 
app.import('app/styles/css/perfect-scrollbar.css')
app.import('vendor/js/perfect-scrollbar.js');

--> vendor > js > perfect-scrollbar.js
--> app > styles > css > perfect-scrollbar.css

2. aa.js

Ember.$(".contentHolder").perfectScrollbar();

3.aa.hbs
 class="contentHolder"

**Comment by noraesae** [comment]
It seems that we do have a module named `EventManager` and it overwrite a module having the same name in `ember-cli`. But I think it shouldn't overwrite the original one because it is a separated CommonJS module. I assume it's a bug of how ember-cli itself handle `require`. As a workaround, you can rename every `EventManager` occurrence to something else in the source code.

If there's any further problem, feel free to let me know.

Cheers,

**Comment by hannah111029** [comment]
@noraesae 

thanks~ Try i'll.

**Comment by noraesae** [comment]
I'll close the issue. If you have any further problem, feel free to reopen it and ask me.

Cheers,
