### ISSUE TITLE
Can perfect-scrollbar auto update itself?

### ISSUE THREAD

**Issue by ObaidUrRehman** [noraesae/perfect-scrollbar#305]
Can perfect-scroll auto update itself when content is dynamically added to a container without actually calling the update() function?

**Comment by noraesae** [comment]
There's no way to update by itself. Nevertheless, `update` is called when a user scrolls the container, so even though we don't update, it will update the size when starting scrolling. But users can see the wrong size of scrollbars before they start scrolling. It can frustrate users, and that's why I recommend calling `update` manually when the content is actually updated.

However, you may be able to find some jQuery plugins which can monitor the resize of an element and propagate an event when it's updated. If you use perfect-scrollbar with the plugins, it may give an answer you may want.

**Comment by zomp** [comment]
Just for a reference, there has already been created an enhancement request #268 to handle automatic updates by HTML5's MutationObserver.

**Comment by noraesae** [comment]
Yes, I've noticed it, but not yet had enough time to look into it. Very sorry guys, and any contribution will be welcomed.

**Comment by ObaidUrRehman** [comment]
Thanks @noraesae . Appreciate your quick feedback.

**Comment by zomp** [comment]
Hi @noraesae, no worries, you have a lot... :-)

**Comment by prashu421** [comment]
Can anyone check at this fiddle and tell me how to use update function in my case.
It simply doesn't work when I tried placing the update function at other button click calls.

https://jsfiddle.net/prashu421/egkfxzrt/

Thank you.

**Comment by utatti** [comment]
@prashu421 You should apply `.update()` to the ps instances. Also, please beware that it should be called after the toggle transition is complete. I've updated the fiddle:

https://jsfiddle.net/egkfxzrt/14/

**Comment by prashu421** [comment]
Yes sir, will remember that. Appreciate your quick response. 
Thank you.
