### ISSUE TITLE
Unexpected Scroll

### ISSUE THREAD

**Issue by Kylia669** [noraesae/perfect-scrollbar#317]
add perfect scroll bar in bootstrap popover( this popover contains form elements with labels )
when trying to select label and drag mouse to down
scroll bar start scroll infinitly all time to down -
and sometimes  in other direction

**Comment by noraesae** [comment]
Hi,

Infinite scrolling is usually caused by padding, margin or absolutely positioned elements, all of which increase `scrollHeight` infinitely in some cases. So, you can start from checking these properties.

If you can't narrow down the reason, please feel free to ask me again. An example page or a fiddle which can reproduce the problem may be helpful.

Thanks :)

**Comment by Justin-lu** [comment]
`perfect-scrollbar`  will bind the `mousemove`  by `bindSelectionHandler` when you have some selection.
You can read [it](https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/selection.js) for details.

**Comment by noraesae** [comment]
Closed for inactivity. Please feel free to reopen.

Thanks!
