### ISSUE TITLE
Scrollbar does not appear when container content changes

### ISSUE THREAD

**Issue by chrissound** [noraesae/perfect-scrollbar#337]
Hi there, please see reproduced here: http://jsfiddle.net/nmndpzku/

**Comment by noraesae** [comment]
As in the old versions, the update call doesn't refill the scrollbars that have been removed by `.html()`. Please use the latest version of the plugin.

Thanks,

**Comment by chrissound** [comment]
Ah it was the latest version on cdnjs.

**Comment by noraesae** [comment]
I've just updated the fiddle with the latest version, and as you can see, it works well.

http://jsfiddle.net/45ofk0zw/

Sadly, you can't use the source files uploaded on the fiddle, because they're just hosted in my mini server.

Sadly, perfect-scrollbar in cdnjs is not maintained by me. I guess somebody made it. Anyway I'll update the cdn for you today.

Thanks.

**Comment by chrissound** [comment]
Have a great day! Thanks for the quick response!

**Comment by noraesae** [comment]
PR is uploaded here: https://github.com/cdnjs/cdnjs/pull/4657

Please wait till it's updated, hopefully soon :smile:
