### ISSUE TITLE
A workaround when position is unset.

### ISSUE THREAD

**Issue by vanduzled** [noraesae/perfect-scrollbar#346]
I'm using this scrollbar for my nav-menu in wordpress. I have a list of menu items that expands beyond the nav container (also my ps-scrollbar container) and is displayed inline. I also have sub-menu and that submenu is located at the bottom of the my body container (outside of nav container). Now the only way to put it outside the nav container is to not put postion: relative on nav container since the sub menu is absolute and that will hide it if the nav container is relative.

Is there a workaround on this one? Here's a js fiddle on what I'm trying to achieve. Remove the position: relative on #nav-container and you'll see how I want it to look like.

http://jsfiddle.net/vanduzled/ndboyf6k/

**Comment by noraesae** [comment]
This issue is technically difficult to fix simply by a simple workaround. Because the plugin uses positioning to display the scrollbars everywhere, the whole logic should be changed when we'd like to remove `position`.

All I can suggest is manipulating DOM completely, such as removing the submenu from the main container and placing them dynamically, or using another subcontainer, etc.
