### ISSUE TITLE
wheel-propagation="true" seems to only work when scrolling up.

### ISSUE THREAD

**Issue by BannedForLife** [noraesae/perfect-scrollbar#369]
wheel-propagation="true" seems to only work when scrolling up and not when scrolling down.

**Comment by noraesae** [comment]
I've just tested 'examples/options-wheelPropagation.html' with the latest Chrome, Safari and Firefox in OS X and it works well. Does the problem occur only in your use case or generally?

**Comment by BannedForLife** [comment]
It seems to be happening on the inner-most scrolbar of nested scrollbars. I can scroll up but scroll does not propagate downwards. Ill see about getting a plunkr/codepepen together.

**Comment by noraesae** [comment]
I've not yet tested for nested scrollbar and now it sounds quite likely to happen. The codepen or something like that must be extremely helpful to narrow down the reason.

Thanks!

**Comment by BannedForLife** [comment]
Here is a link to a codepen that shows the problem. The red div in the is scrollabel but will not propagate down to the image. The codepen uses perfect-scrollbar not angular-perfect-scrollbar which makes me think it is not necessarily a problem with angular-perfect scrollbar. Anyway here is the codepen: http://codepen.io/Labirintami/pen/OPRWWY    I will raise it as an issue on perfect-scrollbars github page also.

**Comment by BannedForLife** [comment]
I just realised that you maintain both so I will not post it in perfect-scrollbar.

**Comment by noraesae** [comment]
In your code there was no specified `stopPropagation` option and it works as expected when I added the line. Please check the following codepen.

http://codepen.io/anon/pen/jPXWrJ

And sadly angular-perfect-scrollbar is not maintained by me. If it's the problem is concerning angular-perfect-scrollbar, please contact to its contributors.

**Comment by clementprevot** [comment]
Hi!

I've been confronted to the exactly same problem as you were. The wheel propagation works well going up but not going down.
However, the CodePen you provided @noraesae was working very good.

It occurs that my problem, and probably the problem of @BannedForLife was due to some rounding in the ```bindMouseWheelHandler.shouldPreventDefault()``` : you first get the ```scrollTop``` of the scrolled element. In my case, it gave me 711.888888px. Then, later you compare it with ```i.contentHeight - i.containerHeight``` which in my case gave me 712px. So, the scroll propagation is stopped.

If you add some ```Math.ceil()``` everywhere (for the ```scrollTop``` attribute and the ```i.contentHeight - i.containerHeight``` operation) it works like a charm.

@noraesae Do you confirm that this can solve the problem? Do you want me to make a pull request or can you fix this in the master by yourself?

Whatever, thank you very much for this beautiful and very really super duper usefull plugin! :+1: :wink:

**Comment by BannedForLife** [comment]
My problem was due to padding on the top and bottom of an md-card. This padding meant I never actually hit the bottom of the card and thus the scroll was never propagated.

**Comment by clementprevot** [comment]
Thanks for letting me know. However, I don't have any padding (and certainly not of 0.2222 px :smile:)

**Comment by noraesae** [comment]
I guess the problem @clementprevot may be similar to #333, in terms of the fact that it is caused by a floating point numbers. I guess the floats should be converted to int whenever needed to do so.

Thanks!
