### ISSUE TITLE
scroll inertia

### ISSUE THREAD

**Issue by cazacugmihai** [noraesae/perfect-scrollbar#399]
Please add support for setting the amount of scrolling momentum (as animation duration in milliseconds).
The behavior can be seen accessing the [demo page](http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/complete_examples.html) of [malihu-custom-scrollbar-plugin](https://github.com/malihu/malihu-custom-scrollbar-plugin).

A quote from the documentation of the mentioned plugin:
> scrollInertia: integer
> Set the amount of scrolling momentum as animation duration in milliseconds.
> Higher value equals greater scrolling momentum which translates to smoother/more progressive animation. Set to 0 to disable.

**Comment by noraesae** [comment]
Hi, first of all, thank you for the interest. However, I'm afraid this feature may not be supported, as I want to make this plugin working the same as the native scroll works as much as possible. It means that implementing momentum is up to the browser, not to JavaScript scripts.

The main reason I think like above is that some browsers and even some mouse drivers implement their own momentum function, and thus I can't be sure that our own implementation doesn't make collision with them. I also think that it will also cause performance issues due to the timers and animations. They are not cheap at all(hooking the scroll event itself is also not cheap by the way).

I am really sorry again, and I really appreciate your suggestion. Forking the plugin and modifying it is completely free.

Thanks!

**Comment by cazacugmihai** [comment]
Hi, 

OK, it makes sense. Thanks for the feedback!

Best regards,
Mihai
