### ISSUE TITLE
Custom events not working?

### ISSUE THREAD

**Issue by bewards** [noraesae/perfect-scrollbar#404]
Set up a jsfiddle here: http://jsfiddle.net/ndboyf6k/17/

Custom scroll events not firing on mouse-wheel scroll, but works with on click. Can this be updated?

**Comment by DanielApt** [comment]
With me it seems to be working when using the mousewheel, keyboard arrows,
and dragging the track.

On which device are you scrolling, and how?

On Mon, Oct 19, 2015 at 5:46 PM, Ben Sewards <notifications@github.com>
wrote:

> Set up a jsfiddle here: http://jsfiddle.net/ndboyf6k/17/
>
> Custom scroll events not firing, did I set it up wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/noraesae/perfect-scrollbar/issues/404>.
>



-- 
This e-mail and any attachments to it are confidential and may also be
legally privileged. If you are not the addressee or have otherwise received
it in error, you are on notice of its status. Please telephone or email the
sender and delete this e-mail. If you are not the addressee, please do not
copy this e-mail or attachments or use it for any purposes, or disclose the
contents to any other person.

For further information about Knowsis Limited, please see our website at
http://www.knows.is

**Comment by forivall** [comment]
Confirmed, no events on mousewheel down; win 7, chrome 46.0.2490.71

**Comment by bewards** [comment]
Same machine and chrome ver. as forivall.

I believe tracking mousewheel solely is handled with the "DOMMouseScroll mousewheel" event, seen here: http://jsfiddle.net/honk1/gWnNv/7/

**Comment by forivall** [comment]
The events are fired properly in Firefox (41.0.2), but this but is reproduced in chrome (same ver), Arch Linux + Gnome 3.18.1

**Comment by DanielApt** [comment]
Can't reproduce my Chrome Version 46.0.2490.80 (64-bit) with Mac OSX.

Seems like a strange combination of factors.

Thinking about how the events work, there might be an explanation:

Perfect scrollbar works by having multiple handlers for different types of events (e.g. scrolling with the mousewheel, or the keyboard). Normally we pick up the direction of these events and pass it to `updateScroll()` which changes the container's `scrollTop` and dispatched the custom events.

The only exception is the [native-scroll handler](https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/native-scroll.js) which directly calls `updateGeometry()` instead.

`updateGeometry()` doesn't fire the custom events, and I'm guessing that this is explaining the lack of events firing.

I'm not sure in which circumstances the nativeScrollHandler is used as opposed to the mouseWheelHandler, but I think this could be an explanation for why we are not seeing events.

@noraesae when is nativeScrollHandler used as opposed to mouseWheelHandler?

**Comment by zackcote** [comment]
I'm seeing the events in @bewards demo, but not in a project of my own. I'll provide more details asap

**Comment by DanielApt** [comment]
@zackcote got any details to provide?

**Comment by DanielApt** [comment]
Could you please provide a JSFiddle demonstrating the issue? Closing it by next week if there's no response.

**Comment by DanielApt** [comment]
Closed due to inactivity. Please re-open when you have the chance to provide more details.
