### ISSUE TITLE
element.getAttribute is not a function

### ISSUE THREAD

**Issue by mantia11** [noraesae/perfect-scrollbar#438]
Trying to install plugin on the website with AngularJS, but got error :( 
I cannot cope with it, hope for you advice...

What is done:
```javascript
// connections
link href="css/perfect-scrollbar.min.css" rel="stylesheet" type="text/css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
<script src="js/lib/perfect-scrollbar.jquery.js"></script>
<script src="js/lib/perfect-scrollbar.js"></script>

//styles
.carousel-in-circles {
  position: relative;
  overflow: hidden;
  width: 100%; /* I need horizontal scrollbar only */
}

// directive use
<div class="carousel-in-circles" perfect-scrollbar>...</div>

// angularJS directive
angular.module('myproject.directives').
    directive('perfectScrollbar', function () {
        return {
            link: function (el) {
                $(document).ready(function (){
                    $(el).perfectScrollbar();
                });                
            }
        };
    });
```
// error
TypeError: element.getAttribute is not a function
    at getId (http://localhost/Myproject/js/lib/perfect-scrollbar.jquery.js:1299:20)
    at Object.exports.get (http://localhost/Myproject/js/lib/perfect-scrollbar.jquery.js:1334:20)

**Comment by noraesae** [comment]
Sorry for the late response.

I'm not sure why this happens, but at least it shouldn't because `Element.getAttribute` is likely to be supported by any modern browser. You can find a documentation [here](https://developer.mozilla.org/en/docs/Web/API/Element/getAttribute). I have no idea about angular, but it may concern it?

A jsfiddle to reproduce the issue may help a lot to narrow down the reason.

**Comment by noraesae** [comment]
Closed for the inactivity.
