### ISSUE TITLE
Scrolling causes continuous browser repaints

### ISSUE THREAD

**Issue by Zenkit** [noraesae/perfect-scrollbar#457]
Hey,

first of all thank you very much for this plugin! I just noticed that if you enable "flash painting" in Chrome, you can see that scrolling inside a perfect scrollbar container causes a lot (!) of repaints. The normal scrollbar of the browser doesn't have that issue. 

Do you have an idea why this is happening? 

Cheers, 
Jesse

**Comment by DanielApt** [comment]
There are plenty of reasons this could be happening, as described [here](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#file-what-forces-layout-md).

Once I have the chance, this is something I'd like to look in to. I believe that there's a lot we can do to improve the rendering performance (and thus address the large amount of repaints). 

Things that I think will be especially useful to address this issue is to:

* use `transform` instead of `top` and `left` positioning
* wrapping the rendering logic inside a `requestAnimationFrame`

**Comment by goldfire** [comment]
Any thoughts on what this would take? The performance issues are pretty much make this a non-starter.

**Comment by noraesae** [comment]
PS has been using `top` and `left` for its simplicity and native scroll compatibility. It will be using them in the future too. Repaints are inevitable, so the best solution will be, as Daniel suggested, using `requestAnimationFrame` to reduce the count. The version 1.0 release will be using `requestAnimationFrame`, which is still in very early stage though.

If performance really suffers because of repaints, my suggestion is:

- Consider using native scrollbar. Please keep in mind that using custom scrollbar is such a bad practice for performance.
- Consider using other custom scrollbars using CSS transform to render the content. It may be difficult to use native JS scroll interface with them though. I cannot suggest any, as I never use, but I guess there are some quality libraries.

**Comment by goldfire** [comment]
It isn't true to say that "repaints are inevitable." If things are done correctly there is no need for repaints at all in many cases. If you are re-writing anyway, I'm not sure why you wouldn't at least explore the possibility of something that could have a significant impact on performance (probably much more than just `requestAnimationFrame`).

**Comment by noraesae** [comment]
Yes, I actually have tested it recently and found it was not true. As you said, repaint doesn't occur just by updating `top` or `left`(thank you for your report again!). I will definitely try avoiding the repaints when writing a new scroll logic.

**Comment by rasmushaglund** [comment]
@utatti is there any road map for doing the rendering improvements? I tried separating some dom reads from dom writes to avoid forced reflows, and that improved the performance a bit, but I feel that making a proper fix would take more effort. Are you working on it, or have any plan for how it should be done?

**Comment by fxck** [comment]
Why is rail using top / left instead of transform?
