### ISSUE TITLE
Is it possible to use jQuery(window).scroll(); command

### ISSUE THREAD

**Issue by gvnet** [noraesae/perfect-scrollbar#460]
Hi,
I am using a theme that has perfect-scrollbar.js. I am also trying to use some svg animations that rely on jQuery(window).scroll(); command to trigger them but it seems perfect-scrollbar.js turns off the default scroll event on the page?
Is there any way I can use perfect-scrollbar.js and still trigger the jQuery(window).scroll(); command ?
Many thanks.

**Comment by DanielApt** [comment]
The scroll event does take place on the perfect-scrollbar container, would it be useful to add the handler there instead of on the window? [Here's a demo](https://jsfiddle.net/DanielApt/yu63ufcj/)

Scrolling is captured by perfect-scrollbar. If you want the scroll event to bubble up to the window once you've reached the end of the container, [`wheelPropogation`](https://github.com/noraesae/perfect-scrollbar#wheelpropagation) might be useful to look at.

Please let me know if you need any help.

**Comment by gvnet** [comment]
Hey Daniel,
Thanks so much for the reply. It turns out the theme I have uses the skrollr library and native scrolling is turned off to allow parallax scrolling on mobile/ios devices (via css transforms). This prevents the animations software from triggering based on the viewport settings as it is not technically scrolling.
Thanks again.
