### ISSUE TITLE
Events for when scrolling stops?

### ISSUE THREAD

**Issue by hillgendorf7** [noraesae/perfect-scrollbar#475]
There's events for scrolling (ps-scroll-y, ps-scroll-x, etc.), but what about when scrolling stops? This would be a great option to have. 

Thanks!

**Comment by noraesae** [comment]
This can be easily implemented with a timer like this example: http://jsfiddle.net/d48bdzba/2/

But we are very careful to accept this as a feature because using timer is usually expensive. I cannot promise but I'll check if there's a way to implement this effectively. Surely, any help will be welcomed!

Thanks.

**Comment by noraesae** [comment]
I think I close this now as the example may be helped. Any PR on this issue will be always welcomed!
