### ISSUE TITLE
if el display:none when ps initializes, when el is visible scrollbar is hidden until scroll event

### ISSUE THREAD

**Issue by plagasul** [noraesae/perfect-scrollbar#476]
https://jsfiddle.net/gbfLazpx/55/

I know this IS in the FAQ, but since it is a little bit specific I though I would post my workaround, maybe not the right place? In any case:

If an element has display:none when ps is applied to it, and then the element is made visible with jquery fadeIn, the scrollbar is hidden until first scroll on the element.

I solved this applying ps within the function that runs after the fadein animation runs, like this:

https://jsfiddle.net/gbfLazpx/56/

**Comment by noraesae** [comment]
You're doing correctly. The issue is because when the element is hidden, PS cannot calculate the geometries of scrollbar components, such as the lengths, offsets, etc. To fix the problem, you can call `.perfectScrollbar('update')` after showing the element. Here is the updated fiddle for the example:

https://jsfiddle.net/gbfLazpx/71/

Thanks!
