### ISSUE TITLE
jQuery UI sortable's option scroll doesn't work

### ISSUE THREAD

**Issue by kaganvmz** [noraesae/perfect-scrollbar#483]
The page doesn't scrolls when item coming to an edge.

**Comment by kstover** [comment]
I had created an issue earlier, but I never had time to actually post a fiddle.

I was able to correct this problem in my use-case by using overflow-y: hidden !important rather than overflow:hidden !important. I only need to scroll on the Y axis, so this worked for me and allowed the sortable to scroll.

So, the CSS looks like:

.ps-container {
    overflow:auto !important;
    overflow-y: hidden !important;
}

I hope that helps!

**Comment by noraesae** [comment]
@kaganvmz, can you please check if @kstover's solution works?

**Comment by kaganvmz** [comment]
Thank you for your response, I'll check.

**Comment by noraesae** [comment]
I close this issue now. Please feel free to reopen if there is further problem.

**Comment by jbardnz** [comment]
@kstover solution worked for me. Thanks a lot, saved me at least a couple of hours!
