### ISSUE TITLE
scrollbar position doesn't reset when content change even after calling 'update'

### ISSUE THREAD

**Issue by medBouzid** [noraesae/perfect-scrollbar#511]
my div contains some html and I have applied perfectScrollbar to that div, when I click a button the html inside the div changes and I call perfectScrollbar('update') on the div, but the scrollbar position is still like it remember of the previous position... actually to solve that I am calling `scrollTop(0)` on the div like the following

`$("myDiv").scrollTop(0).perfectScrollbar('update')`

This solve the issue but I am just not sure why it behaves like that, maybe there is something wrong with my code or it's natively like that, I would just suggest to reset the position when calling 'update' because it seems logic ! 

Thanks!

**Comment by DanielApt** [comment]
Could you create a [JSFiddle](https://github.com/noraesae/perfect-scrollbar#jsfiddle)

**Comment by stephanepericat** [comment]
Same issue here

**Comment by DanielApt** [comment]
Continuously checking `scrollHeight` would be a very costly operation, this is why we have built the `update` method.

When you're saying it should not change the position, this doesn't happen in the case of adding content to a container, but it sometimes must happen when content is removed from a perfect scrollbar container.

Here's an example showing what happens when you add/remove content to a perfect scrollbar https://jsfiddle.net/sh7tp0hd/2/

Could you create a JSFiddle demonstrating the issue, I can better address this issue.

**Comment by DanielApt** [comment]
Closing due to inactivty.
