### ISSUE TITLE
v6.11 broke our code

### ISSUE THREAD

**Issue by mmswi** [noraesae/perfect-scrollbar#512]
Hello,

Just to inform you that v6.11 via bower_install broke our code, something like e.perfectScrollbar is not a function.

Had to revert to v6.10

Thanks

**Comment by noraesae** [comment]
Hello, you may have been importing the script from `js/min/perfect-scrollbar.min.js` or `js/min/perfect-scrollbar.jquery.min.js`. Now we unified the folder structure the same with `css`, and the `min` directory is removed. Now the scripts are in `js/perfect-scrollbar.min.js` and `js/perfect-scrollbar.jquery.min.js`. Sorry for the inconvenience. The following issue and commit include the content.

- #472 
- edaeccebf264a5eb3317c2a25448ec3ce3082221

If it's not because of this change, there must be something wrong. Please feel free to reopen the issue if then.

Thanks
