### ISSUE TITLE
`box-sizing:border-box` needed because `inlcudePadding:true` doesn't work

### ISSUE THREAD

**Issue by josephrocca** [noraesae/perfect-scrollbar#519]
Please correct me if I'm wrong, but the need for `box-sizing:border-box;` on elements that have padding is undocumented?

I tried using the `inlcudePadding:true` option but it didn't help.

Here is minimal working example: https://jsfiddle.net/rv77o2L3/1/

If you take away `box-sizing:border-box;` in the css, it breaks. If you add `inlcudePadding:true`, it doesn't fix it. You can see the problem by scrolling all the way to the bottom of the list - it keeps going. Lengthens the size of the list the more you scroll down.

Not an issue for me anymore but it took a while to figure this out, so I figured I'd post an issue just in case I'm not alone in having this difficulty.

Cheers

Edit: P.S. Unrelated, but I also vote for an `alwaysVisible` option rather than having to alter CSS. I understand you're following a design pattern, but the current approach is a lot messier for users of the lib than it has to be.

**Comment by noraesae** [comment]
It seems PS cannot calculate the height properly. It looks like a bug. Thank you for the report. Unfortunately, for the time being I don't have enough time to look into this because of my relocation for a job. I will investigate ASAP. Any contribution will be thoroughly welcomed.

Also, about your suggestion on `alwaysVisible`, I'll open a separated issue. Thanks again!

**Comment by noraesae** [comment]
In v1, PS will use a new method to calculate the size of scrollbars, which works well with `border-box` too. It's still under the heavy development, but you can check a quick look [here](https://jsfiddle.net/pk2f0gsw/2/).

Thanks.
