### ISSUE TITLE
while hovering the popup the parent scrollbar is also visible ? how to visible only the respective scrollbar ?

### ISSUE THREAD

**Issue by rajagopal14** [noraesae/perfect-scrollbar#522]
![screen shot 2016-06-20 at 2](https://cloud.githubusercontent.com/assets/13791804/16195092/ae514bf8-3715-11e6-95d5-3df244e93936.png)

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by rajagopal14** [comment]
Can u please check this also ?

**Comment by rajagopal14** [comment]
Hello there ? Can u Please tell Y this is happening ?

**Comment by noraesae** [comment]
This is because we use CSS to make it visible with the `:hover` pseudo class. It is impossible to stop propagation of `:hover` only by CSS. I would recommend modifying `:hover` to something like `.hover` in CSS and manually applying the class with scripts. It can be done without changing perfect-scrollbar's JS code.
