### ISSUE TITLE
If I scroll from a Iframe am not able to scroll? why ? Pls check the jsfiddle

### ISSUE THREAD

**Issue by rajagopal14** [noraesae/perfect-scrollbar#528]
https://jsfiddle.net/gbfLazpx/193/

Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by rajagopal14** [comment]
@noraesae Any update about this ?

**Comment by rajagopal14** [comment]
@noraesae Hi Any update regarding this ?

**Comment by noraesae** [comment]
First, you may not able to scroll `google.com` because of cross-origin limitation. If you'd like to use it for an iframe with the same origin as the container page, please refer to the [iframe example](https://github.com/noraesae/perfect-scrollbar/blob/master/examples/iframe.html) and other issues. I personally don't recommend using PS for iframes though, as it's just not an appropriate container.

**Comment by rajagopal14** [comment]
Yeah I understand, but dont need PS for an iFrame. I need If I scroll from that Iframe parent scroll is not happening

**Comment by rajagopal14** [comment]
parent container has PS. If I hover the iFrame and scroll from Iframe parent scroll is not happening do you understand what am trying to explain?

**Comment by noraesae** [comment]
I understand. It's because the scroll event is happening in the iframe and we cannot capture the event in the container because of, as I said, cross-origin limitation. If you would like to bubble up the scroll event from iframe to container, you should manually handle scroll event and propagate it to the container frame.

**Comment by noraesae** [comment]
I don't understand. Can you please explain more?

**Comment by rajagopal14** [comment]
u said scroll event is happening in iframe that's why parent scroll is not happening due to cross-origin limitation right.
but if child element is div instead of iFrame its working fine why ?

**Comment by noraesae** [comment]
Because div is just a normal container element. Cross origin doesn't apply to `div` and also scroll event is not trapped in `div`. `div` and `iframe` are basically just different.

**Comment by rajagopal14** [comment]
ok thank you

**Comment by rajagopal14** [comment]
can you give any sample example to propagate container from iframe ?

**Comment by noraesae** [comment]
You can refer to my answer in this issue: https://github.com/noraesae/perfect-scrollbar/issues/327

**Comment by rajagopal14** [comment]
ok thankyou
