### ISSUE TITLE
In windows if we click middle button in mouse automatic scroll will enable. but this only working in IE browsers only. Its not working in firefox and chrome.

### ISSUE THREAD

**Issue by rajagopal14** [noraesae/perfect-scrollbar#533]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by rajagopal14** [comment]
@noraesae  Any update regarding this ?

**Comment by rajagopal14** [comment]
@noraesae  Any update on this ?

**Comment by rajagopal14** [comment]
@noraesae Can u pls update this?

**Comment by rajagopal14** [comment]
@noraesae any update on this?

**Comment by noraesae** [comment]
Hello, I'm sorry for the late response.

I'm recently busy for my personal and professional works and response sometimes becomes very late. I will reply whenever possible, so please don't spam 'any update' comments.

About middle click scrolling, PS don't yet support it. IE may use `scroll` event for it, and that's why it works only for IE, as I guess. There is an [issue](https://github.com/noraesae/perfect-scrollbar/issues/412) related with this. I'm not sure when I can work on this, but I always welcome any contribution.

Thanks again.

**Comment by rajagopal14** [comment]
ok thanks. @noraesae  is there any possible ways to solve this issue at my side?

**Comment by noraesae** [comment]
Thank you very much for your understanding.

I think you can implement it manually by hooking middle click, but I'm not sure it works out well. I'm afraid I cannot find a simple workaround.

**Comment by rajagopal14** [comment]
ok thanks for ur update
