### ISSUE TITLE
Is it possible to divide wheelPropagation option to wheelPropagationX&wheelPropagationY?

### ISSUE THREAD

**Issue by Chiakiii** [noraesae/perfect-scrollbar#557]
So..

**Comment by noraesae** [comment]
Currently, it's not supported and I am afraid it may not be supported in the close future. The original purpose of PS is to provide scroll emulation working like the native one, so actually the `wheelPropagation` option was not needed, as in native one it always propagates. It was added because so many people would like it. I may not make the case more complicated.

Sorry that I cannot help in this case, but you can freely fork the project and fix it for your use case. You can find the code around `shouldPreventDefault` in `src/js/plugin/handler/mouse-wheel.js`. If there is any question while modifying it, please feel free to ask me.

Thanks for your interests again.

**Comment by mercs600** [comment]
For example I had to use vertical mousewheel to horizontal scroll. 
When I set useBothWheelAxes on true wheelPropagation doesn't work anymore.  I added wheelPropagationX option to use only vertical mousewheel and prevent scroll when scrollLeft is equal to width of container. 

@noraesae it would be nice if you could check it: 
https://github.com/mercs600/perfect-scrollbar/commit/36979b1e9c1ccb07be43fe435cd25d88db0ab4e1
