### ISSUE TITLE
How to scroll perfect scrollbar with keyboard up and down keys

### ISSUE THREAD

**Issue by sudhirbeldar** [noraesae/perfect-scrollbar#559]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [x] Provide a page or source code where the issue can be checked

**Comment by DanielApt** [comment]
You need to make sure that the container is the focused element.

For example, in [this JSFiddle](https://jsfiddle.net/DanielApt/xv0rrxv3/) pressing the keyboard does not scroll.

Only after clicking the container, does keyboard scrolling work.

If it still isn't working, please let me know and I will re-open this issue.

**Comment by sudhirbeldar** [comment]
Hello Daniel,

Thank you very much immediate reply. 

In my case, I have a search text box, wherein user types and search results auto populates. I have appended Perfect scrollbar on search results. In this case my focus is on search text box. I have added jquery to show highlight on search results when user press keyboard down key (ASCII value 40). and there after up and down keys for navigation. 

Could you please help me to set focus on ps-container when first down key is pressed or any other suggestion.

**Comment by DanielApt** [comment]
Ah… I understand.

Because the search text box has focus, the perfect-scrollbar container will not receive any focus.

You can listen to arrow key presses within the search box and then scroll the container. You can see how I've done that [here](https://jsfiddle.net/gbfLazpx/259/).

I **strongly** advise against this approach. By default when an element is being typed into, the browser will not allow scrolling past it. You'll notice this in Google Chrome in the example I shared.

**Comment by sudhirbeldar** [comment]
Hey Daniel,

Thank you very much. It resolves my issue. I will further ask you question if I again get stuck in this context.

Thank you very much for your help.
