### ISSUE TITLE
Not working on html tag

### ISSUE THREAD

**Issue by Dylavemiliak** [noraesae/perfect-scrollbar#563]
Hello,

first of all, your plugin is wonderful, I'm appreciating it very much.

Just one question, I'm trying to get it work on html tag, the scrollbar appear but aren't scrollable, have you some suggestion?

Thank you in advance for you help and, again, for the great work!

Bye

**Comment by noraesae** [comment]
Hi,

First of all thank you very much for your praise.

Using PS in `html` or `body` is not recommended, because they are not a typical DOM element. PS is not ensured to work with them. Please consider creating a `div` having full width and height, or just using browsers' native scroll(global scroll hooking is a bad practice!).

**Comment by Dylavemiliak** [comment]
Ok, thank you and keep the excelent work! ;)

Bye
