### ISSUE TITLE
Being able to disable y and x rail auto position

### ISSUE THREAD

**Issue by jakkor** [noraesae/perfect-scrollbar#564]
It would be good if we could disable setting right and bottom position of rails by javascript, so for example the setting could be:

y-rail-position-top: 0 - means that it will always be 0,
auto - for current behaviour.
The same for y-rail-position-left: 0, and similar things for x-rail.

The reason for this is that for example in my case I am doing the scroll of the container manually, and when scrolling for example horizontally right when the y-rail position changes to -50px it's not visible on the screen.

I can do that with css

ps-scrollbar-y-rail {
    right: 0 !important;
}

But I don't want to use important really, and I not sure if it will work everywhere when css style will be set to 0, and inline style to -100px for example.

I can try to prepare some pull request if you are fine with this change.

**Comment by noraesae** [comment]
You shouldn't set them. Rails are moving because they are *inside* the container, and the container scrolls. Absolute positioned elements are positioned relative to its positioned parent.

I'm not sure what's your case, but the rails should display well without any extra styles. Can you provide a fiddle to explain your case?

**Comment by noraesae** [comment]
Closed for its inactivity. Please feel free to reopen if there is further information.
