### ISSUE TITLE
Scrolling content page-by-page by clicking on the rail

### ISSUE THREAD

**Issue by tukasz** [noraesae/perfect-scrollbar#568]
Is there any way to get a functionality similar to native scroll bars, i.e.: when user clicks on the rail below the scroller, the view is scrolled one **page** down and when user clicks in the rail above the scroller, the view is scroller one **page** up.
If not then I guess it would be a usefull feature to have in the PS.

**Comment by pietervandergijp** [comment]
I am not part of the contributors but this can be real easy realized by Adding/Replace the following code in the click-rail.js.

var dom = require('../../lib/dom');
var _ = require('../../lib/helper');
var instances = require('../instances');
var updateGeometry = require('../update-geometry');
var updateScroll = require('../update-scroll');

function bindClickRailHandler(element, i) {
  function pageOffset(el) {
    return el.getBoundingClientRect();
  }
  var stopPropagation = function (e) { 
	  e.stopPropagation(); 
  };
 
/******* Vert Scrollbar *****/
   	var destY = null;
   	var currentTop = null;
	var startTime;
	
 	var calcTopScrollPos = function(pageY) { 
		
		var halfOfScrollbarLength = _.toInt(i.scrollbarYHeight / 2);
		var positionTop = i.railYRatio * (pageY - window.pageYOffset - pageOffset(i.scrollbarYRail).top - halfOfScrollbarLength);
		var maxPositionTop = i.railYRatio * (i.railYHeight - i.scrollbarYHeight);
		var positionRatio = positionTop / maxPositionTop;

		if (positionRatio < 0) {
			positionRatio = 0;
		} else if (positionRatio > 1) {
			positionRatio = 1;
		}

		return (i.contentHeight - i.containerHeight) * positionRatio;
	};

	var calcAbsTopScrollPos = function(e) { 

		return _.toInt(e * (i.railYHeight - i.scrollbarYHeight) / (i.contentHeight - i.containerHeight));
	}
	
	function updateScrollTop(newTop) {

		updateScroll(element, 'top', newTop);
	    updateGeometry(element);
    }

	function moveScrollTop(deltaY) {
	    
		var newTop = currentTop + (deltaY * i.railYRatio);
		updateScrollTop(newTop);
	}	

	var scrollTop = function() {
		
		if (destY == null)
			return;
			
		currentTop = element.scrollTop; // * i.railYRatio;
		
		var diffY = destY - currentTop;
		if (Math.abs(diffY)<=90*i.railYRatio) {
			updateScrollTop(destY);
			//updateScroll(element, 'top', destY);
			//updateGeometry(element);
			return;
		}
		
		moveScrollTop((diffY>90)?90:-90);
		
		setTimeout(function() {
			scrollTop();
		}, 50);
	};

	var mouseMoveHandlerScrollbarYRail = function(e) {
		
		destY = calcTopScrollPos(e.pageY);
		scrollTop();
			
		e.stopPropagation();
		e.preventDefault();
	};

	i.event.bind(i.scrollbarYRail, 'mousedown', function(e) {
		
		mouseMoveHandlerScrollbarYRail(e);
		//currentPageY = e.pageY;
		//currentTop = _.toInt(dom.css(i.scrollbarY, 'top')) * i.railYRatio;
		_.startScrolling(element, 'y');
		startTime = (new Date()).getTime();
		
		i.event.bind(i.ownerDocument, 'mousemove', mouseMoveHandlerScrollbarYRail);
		i.event.once(i.ownerDocument, 'mouseup', function() {
			_.stopScrolling(element, 'y');
			i.event.unbind(i.ownerDocument, 'mousemove', mouseMoveHandlerScrollbarYRail);
			
			if ((new Date()).getTime()-startTime < 200)
				//handle it as click event
				updateScrollTop(destY);
			
			//stopAutoscroll
			destY = null;
		});
	});
/*
 	 //removed because can cause interference
	 if (i.settings.stopPropagationOnClick) {
	    i.event.bind(i.scrollbarY, 'click', stopPropagation);
	  }

	  i.event.bind(i.scrollbarYRail, 'click', function (e) {
		  
		updateScrollTop(calcTopScrollPos(e.pageY));
		e.stopPropagation();
	  });
*/
	
/******* Hor Scrollbar *****/
	
	var destX = null;
	var currentLeft = null;
	var startTime;

	var calcTopScrollLeft = function(pageX) { 
	
		var halfOfScrollbarLength = _.toInt(i.scrollbarXWidth / 2);
		var positionLeft = i.railXRatio * (pageX - window.pageXOffset - pageOffset(i.scrollbarXRail).left - halfOfScrollbarLength);
		var maxPositionLeft = i.railXRatio * (i.railXWidth - i.scrollbarXWidth);
		var positionRatio = positionLeft / maxPositionLeft;

		if (positionRatio < 0) {
	  		positionRatio = 0;
		} else if (positionRatio > 1) {
	  		positionRatio = 1;
		}

		return ((i.contentWidth - i.containerWidth) * positionRatio) - i.negativeScrollAdjustment;
	};

function updateScrollLeft(newLeft) {

    updateScroll(element, 'left', newLeft);
    updateGeometry(element);
}

function moveScrollLeft(deltaX) {
    
	var newLeft = currentLeft + (deltaX * i.railXRatio);
	updateScrollLeft(newLeft);
}	

var scrollLeft = function() {
	
	if (destX == null)
		return;
		
	currentLeft = element.scrollLeft;
	
	var diffX = destX - currentLeft;
	if (Math.abs(diffX)<=90*i.railXRatio) {
		updateScrollLeft(destX);
		return;
	}
	
	moveScrollLeft((diffX>90)?90:-90);
	
	setTimeout(function() {
		scrollLeft();
	}, 100);
};

var mouseMoveHandlerScrollbarXRail = function(e) {
	
	destX = calcTopScrollLeft(e.pageX);
	scrollLeft();
		
	e.stopPropagation();
	e.preventDefault();
};

i.event.bind(i.scrollbarXRail, 'mousedown', function(e) {
	
	mouseMoveHandlerScrollbarXRail(e);
	_.startScrolling(element, 'x');
	startTime = (new Date()).getTime();
	
	i.event.bind(i.ownerDocument, 'mousemove', mouseMoveHandlerScrollbarXRail);
	i.event.once(i.ownerDocument, 'mouseup', function() {
		_.stopScrolling(element, 'x');
		i.event.unbind(i.ownerDocument, 'mousemove', mouseMoveHandlerScrollbarXRail);
		
		if ((new Date()).getTime()-startTime < 150)
			//handle it as click event
			updateScrollLeft(destX);
		
		//stopAutoscroll
		destX = null;
	});
});

/*
	//removed because can cause interference
	 
  	if (i.settings.stopPropagationOnClick) {
    	i.event.bind(i.scrollbarX, 'click', stopPropagation);
  	}
  
  	i.event.bind(i.scrollbarXRail, 'click', function (e) {
    
		updateScrollLeft(calcLeftScrollPos(e.pageX));
     	e.stopPropagation();
  	});
*/
}

module.exports = function (element) {
  var i = instances.get(element);
  bindClickRailHandler(element, i);
};**

PS the click scroll is still maintained but can be disabled is required

**Comment by TyGp** [comment]
df

**Comment by noraesae** [comment]
This looks like a right rail-click handling. Will work on this.

**Comment by noraesae** [comment]
Fixed. Thanks!

**Comment by tukasz** [comment]
Hi Jun,

Thanks a lot for the fix. 
Does it mean that user needs to right-click on the rail above/below scrollbar to scroll the view one page up/down?
If so, why not go for the left click? Or even make it configurable? :)

**Comment by noraesae** [comment]
Sorry for the bad English. The 'right' means 'correct'. It means it's the correct way to handle click-rail. It surely works with left click 😄

**Comment by tukasz** [comment]
Oh, no problem :). In such case thank you again for the fix and great overal work on the PS :)
