### ISSUE TITLE
Scroll inside iframe

### ISSUE THREAD

**Issue by Iworb** [noraesae/perfect-scrollbar#580]
Found one more strange behavior. When you put a scrollbar inside iframe window and then scrolling it using scrollbar (not mouse wheel) it's doesn't react when mouse move or key up ouside of iframe.

**Comment by noraesae** [comment]
As found in other former issues, using a DOM based custom scrollbar in iframe is somewhat tricky. perfect-scrollbar is not designed to work well with non-container tags such as `iframe` or `textarea`. There is a limited case where it works and it's provided as [an example](https://github.com/noraesae/perfect-scrollbar/blob/master/examples/iframe.html). You may consider running it in a web server(`gulp serve`) because of iframe cross-origin.

If it doesn't apply well to your case, please consider using native scrollbar.

**Comment by monstrfolk** [comment]
@utatti, What happened to the example?
