### ISSUE TITLE
Disable scroll fading?

### ISSUE THREAD

**Issue by mlibre** [noraesae/perfect-scrollbar#599]
Any option to disable fading?

**Comment by noraesae** [comment]
What do you mean with scroll fading?

If you means scroll easing, we do not specifically add additional scroll effect. If there seems to be fading, it's because the browser makes it work like that. This is intended and may not be changed.

If you means scrollbar fading on display/hide, it can be easily disabled by modifying CSS. Please remove transition properties from CSS.

**Comment by mlibre** [comment]
ok. :+1:

**Comment by MennoVS** [comment]
@noraesae I've come across a scenario involving a slow device and a heavy app, making scrolling slow. To increase the speed of the application I'd like to disable scroll easing. I've looked around in the code and found an 'easingLoop' on touchEnd, disabling it increases scrolling usability. 

I'd like to add a setting to disable this loop. I'll submit a PR for it, please let me know what you think.
