### ISSUE TITLE
Feature Request : Publish Scrolling Events on Container

### ISSUE THREAD

**Issue by WebStew** [noraesae/perfect-scrollbar#94]
Would it be possible to publish some custom events when the container is either being scrolled on the X or Y plane so that we are able to hook in.

**Comment by DanielApt** [comment]
It'd be nice to not only trigger events for which axis is being scrolled, but in which direction. So we'd have events called `ps-scroll-up`, `ps-scroll-down`, etc.

The issue is that I can't bind to `scroll` event, because they don't bubble up, which is required for my scenario.

Also the gist doesn't work with PerfectScrollbar, as the library has changed a lot since then.
